# -*- coding: utf-8 -*-
"""1.2 Modern Network Architectures Elvis Avduli E22001.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHpb6g3UtNeXwoiN9FFraSgqeMgB444b
"""

# Function to calculate the delays
def calculate_delays(K, v, C, L):
    # Transmission delay from sensor S to the edge node E
    delay_edge = (v / K) * (L / C)  # only needs to go up to node v

    # Transmission delay from sensor S to the server Srv
    delay_server = (L / C)  # assuming it travels from sensor to the last node

    # Difference in delay
    delay_difference = delay_server - delay_edge

    return delay_edge, delay_server, delay_difference

# Function to get a valid integer input
def get_valid_int(prompt):
    while True:
        try:
            value = int(input(prompt))
            if value <= 0:
                print("Please enter a positive integer.")
            else:
                return value
        except ValueError:
            print("Invalid input. Please enter a valid integer.")

# Function to get a valid float input
def get_valid_float(prompt):
    while True:
        try:
            value = float(input(prompt))
            if value <= 0:
                print("Please enter a positive number.")
            else:
                return value
        except ValueError:
            print("Invalid input. Please enter a valid number.")

# Function to get a valid 'v' value (the edge node index)
def get_valid_v(prompt, K):
    while True:
        try:
            value = int(input(prompt))
            if value <= 0:
                print("Please enter a positive integer.")
            elif value >= K:
                print(f"Please enter a value less than {K}.")
            else:
                return value
        except ValueError:
            print("Invalid input. Please enter a valid integer.")

# Main function to run the program
def main():
    print("Welcome! This program calculates the transmission delay between nodes.")

    K = get_valid_int("Insert the number of nodes you have: ")
    v = get_valid_v(f"Enter the node index where Edge Node E is placed (v, 1 to {K-1}): ", K)

    # Input bit rate and packet size in bits for consistency
    C = get_valid_float("Insert bit rate in Mbps: ") * 1_000_000  # Convert Mbps to bits per second
    L = get_valid_float("Insert packet size in Mbytes: ") * 8_000_000  # Convert Mbytes to bits (1 MB = 8 million bits)

    # Calculate delays
    edge_delay, server_delay, delay_diff = calculate_delays(K, v, C, L)

    # Output the calculated results
    print(f"\nResults:")
    print(f"Edge Node Delay: {edge_delay:.6f} seconds")
    print(f"Server Delay: {server_delay:.6f} seconds")
    print(f"Delay Difference: {delay_diff:.6f} seconds")

if __name__ == "__main__":
    main()