# -*- coding: utf-8 -*-
"""1.1 Computer Networking II Elvis Avduli, e22001.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ki1afaYfZou3eGPxjVjhrVA98Dl8I1gr
"""

def get_positive_float(prompt):
# Helper function to get a positive float from the user.

    while True:
        try:
            value = float(input(prompt))
            if value <= 0:
                print("Please enter a positive number.")
            else:
                return value
        except ValueError:
            print("Invalid input. Please enter a valid number.")


def get_packet_sizes():
# Function to get packet sizes from the user.

    packet_sizes = []
    print("Enter packet sizes in MBytes (type 'done' when finished):")
    while True:
        user_input = input("Packet size (MBytes): ")
        if user_input.lower() == 'done':
            if len(packet_sizes) > 0:
                return packet_sizes
            else:
                print("Please enter at least one packet size.")
        else:
            try:
                size = float(user_input)
                if size > 0:
                    packet_sizes.append(size)
                else:
                    print("Please enter a positive number.")
            except ValueError:
                print("Invalid input. Please enter a valid number.")


def calculate_delays(packet_sizes, bitrate, propagation_delay, processing_delay, queuing_delay):
    # Convert bitrate from Mbps to MBps (1 Megabit = 0.125 Megabytes)
    bitrate_MBs = bitrate * 0.125

    total_delay = 0
    delays_per_packet = []

    # For each packet, calculate the total delay
    for packet_size in packet_sizes:
        # Transmission delay: packet size / bitrate
        transmission_delay = packet_size / bitrate_MBs

        # Total delay for the packet
        total_packet_delay = transmission_delay + propagation_delay + processing_delay + queuing_delay
        delays_per_packet.append(total_packet_delay)
        total_delay += total_packet_delay

    # Calculate the average delay
    average_delay = total_delay / len(packet_sizes)

    return delays_per_packet, average_delay


# Main Program
print("Network Delay Calculation Program")

# Get input from user
packet_sizes = get_packet_sizes()
bitrate = get_positive_float("Enter the bit-rate (Mbps): ")
propagation_delay = get_positive_float("Enter the propagation delay (msec): ")
processing_delay = get_positive_float("Enter the processing delay (msec): ")
queuing_delay = get_positive_float("Enter the queuing delay (msec): ")

# Call the function to calculate delays
delays, average_delay = calculate_delays(packet_sizes, bitrate, propagation_delay, processing_delay, queuing_delay)

# Output the results
print("\nResults:")
for i, delay in enumerate(delays, 1):
    print(f"Packet {i} delay: {delay:.2f} msec")
print(f"Average delay: {average_delay:.2f} msec")