# -*- coding: utf-8 -*-
"""2.2. Πρόγραμμα Λογισμικού, Έλβις Αβντούλι,Ε22001 ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uYmwRSm0Q66trd2C02FZGrgpowozFd8o
"""

def calculate_delay(L, C, Prop, queueing_percentage):
    # Υπολογισμός της συνολικής καθυστέρησης
    total_delay = Prop + (L / C)

    # Προσθήκη επιβάρυνσης λόγω καθυστέρησης επεξεργασίας και αναμονής
    total_delay_with_queueing = total_delay * (1 + queueing_percentage / 100)

    return total_delay_with_queueing

def calculate_transmitted_bits(C, t1, t2,Prop):
  Tb1 = 1 / C + Prop

  # bits που θα φτάσουν μέχρι τη χρονική στιγμή t1
  packageTransfer1 = ((t1 - Tb1) / (1 / C)) + 1

  # bits που θα φτάσουν μέχρι τη χρονική στιγμή t2
  packageTransfer2 = ((t2 - Tb1) / (1 / C)) + 1

  # Συνολικό πακέτο που μεταφέρθηκε από τη χρονική στιγμή t1 έως τη χρονική στιγμή t2
  packageTransfer = packageTransfer2 - packageTransfer1

  return packageTransfer

def main():
    # Εισαγωγή δεδομένων από το χρήστη
    while True:
        try:
            L = float(input("Εισάγετε το μέγεθος πακέτου L (σε bits): "))
            if L <= 0:
                raise ValueError("Το μέγεθος πακέτου πρέπει να είναι θετικός αριθμός.")
            break
        except ValueError as ve:
            print(ve)

    while True:
        try:
            C = float(input("Εισάγετε το bit rate C (σε bits): "))
            if C <= 0:
                raise ValueError("Το bit rate πρέπει να είναι θετικός αριθμός.")
            break
        except ValueError as ve:
            print(ve)

    while True:
        try:
            Prop = float(input("Εισάγετε την καθυστέρηση διάδοσης Prop (σε sec): "))
            if Prop < 0:
                raise ValueError("Η καθυστέρηση διάδοσης πρέπει να είναι μη αρνητικός αριθμός.")
            break
        except ValueError as ve:
            print(ve)

    while True:
        try:
            queueing_percentage = float(input("Εισάγετε το ποσοστό επιβάρυνσης λόγω καθυστέρησης επεξεργασίας και αναμονής (%): "))
            if queueing_percentage < 0 or queueing_percentage > 100:
                raise ValueError("Το ποσοστό επιβάρυνσης πρέπει να είναι μεταξύ 0 και 100.")
            break
        except ValueError as ve:
            print(ve)

    # Υπολογισμός συνολικής καθυστέρησης
    total_delay = calculate_delay(L, C, Prop, queueing_percentage)
    print("Συνολική καθυστέρηση: {:.2f} seconds".format(total_delay))

    # Υπολογισμός αριθμού bits που μεταδόθηκαν εντός ενός χρονικού διαστήματος
    while True:
        try:
            t1 = float(input("Εισάγετε το χρονικό σημείο t1 (σε sec): "))
            t2 = float(input("Εισάγετε το χρονικό σημείο t2 (σε sec): "))
            if t2 <= t1:
                raise ValueError("Το χρονικό σημείο t2 πρέπει να είναι μεταγενέστερο από το t1.")
            break
        except ValueError as ve:
            print(ve)

    transmitted_bits = calculate_transmitted_bits(C, t1, t2,Prop)
    print("Αριθμός bits που μεταδόθηκαν εντός του χρονικού διαστήματος: {:.2f}".format(transmitted_bits))

if __name__ == "__main__":
    main()