# -*- coding: utf-8 -*-
"""Ex1, Elvis Avduli, E22001.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1euKbOtUGlmnXdmkTcOXv4i-esr1vZfCc
"""

import math
#Το πρόγραμμα εκτελείτε από το google colab
def main():
    # Ζητάμε από τον χρήστη το εύρος των αριθμών
    valid = True
    while valid:
        First = float(input("Insert the first number for the range: "))
        Last = float(input("Insert the last number for the range: "))

        if Last > First:
            valid = False
        else:
            print("The last number of the range must be bigger than the first.")

    # Ζητάμε από τον χρήστη τον αριθμό των επιπέδων κβαντοποίησης (16 ή 32)
    valid = True
    while valid:
        levels = int(input("Insert the number of levels (16 or 32): "))
        if levels in [16, 32]:
            valid = False
        else:
            print("Choose either 16 or 32 levels.")

    # Ζητάμε από τον χρήστη τον αριθμό των μετρήσεων που θέλει να προσθέσει
    valid = True
    while valid:
        measCount = int(input("Insert the number of measurements you want to add: "))
        if measCount >= 1:
            valid = False
        else:
            print("The number of measurements must be bigger or equal to 1.")

    sequence = []

    # Ζητάμε από τον χρήστη τις μετρήσεις και ελέγχουμε αν βρίσκονται εντός του εύρους
    for i in range(measCount):
        while True:
            measurement = float(input("Insert one number for your sequence: "))
            if First <= measurement <= Last:
                sequence.append(measurement)
                break
            else:
                print("The measurement you are giving is not in the number range. Please insert a correct measurement.")

    # Στρογγυλοποιούμε τις μετρήσεις σε ακέραιους και τις ταξινομούμε
    roundSequence = [round(num) for num in sequence]
    roundSequence.sort()

    # Υπολογισμός της τιμής της ομάδας (team_value) για την κβαντοποίηση
    team_value = (Last - First + 1) / (levels - 1)

    values = []

    # Υπολογισμός των τιμών κβαντοποίησης για κάθε μέτρηση
    for num in roundSequence:
        k = team_value
        for j in range(levels):
            if num <= k:
                values.append([num, j])
                break
            k += team_value

    # Εκτύπωση των στρογγυλοποιημένων μετρήσεων
    print("\nYour rounded measurement numbers are:")
    print(" ".join(map(str, roundSequence)))

    # Υπολογισμός του μέγιστου μήκους δυαδικής αναπαράστασης (max_length)
    max_length = math.floor(math.log2(levels)) + 1

    # Εκτύπωση της δυαδικής αναπαράστασης των μετρήσεων
    print("\nYour measurement numbers in Binary are:")
    for num in roundSequence:
        binary_representation = format(num, 'b').zfill(max_length)
        print(binary_representation, end=" ")

if __name__ == "__main__":
    main()