# -*- coding: utf-8 -*-
"""2.1 Building network, CNII, Elvis Avduli, E22001.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UNBN5cNqQ6iZxrgtUN6Wu_3c8ZroowC4
"""

def calculate_cameras_and_bitrate(road_length, camera_range, frame_rate, frame_size, num_colors):
    # Calculate the number of cameras needed
    num_cameras = (road_length // camera_range) + (1 if road_length % camera_range != 0 else 0)

    # Calculate the bit-rate per camera
    bits_per_pixel = num_colors.bit_length()  # Bit depth needed for num_colors
    bits_per_frame = frame_size * frame_size * bits_per_pixel
    bitrate_per_camera = bits_per_frame * frame_rate

    # Total bit-rate required for all cameras
    total_bitrate = bitrate_per_camera * num_cameras

    return num_cameras, total_bitrate

def is_positive_number(value, data_type):
    try:
        value = data_type(value)
        if value > 0:
            return value
        else:
            print("The value must be greater than 0.")
            return None
    except ValueError:
        print("Invalid input. Please enter a number.")
        return None

# Input with validation
road_length = None
while road_length is None:
    road_length = is_positive_number(input("Enter the length of the road (in meters): "), float)

camera_range = None
while camera_range is None:
    camera_range = is_positive_number(input("Enter the range of each camera (in meters): "), float)

frame_rate = None
while frame_rate is None:
    frame_rate = is_positive_number(input("Enter the required frame rate (frames per second): "), int)

frame_size = None
while frame_size is None:
    frame_size = is_positive_number(input("Enter the size of each frame (frame width in pixels): "), int)

num_colors = None
while num_colors is None or num_colors < 2:
    num_colors = is_positive_number(input("Enter the total number of colors for a pixel (must be >= 2): "), int)
    if num_colors is not None and num_colors < 2:
        print("The number of colors must be at least 2.")

# Calculations
num_cameras, total_bitrate = calculate_cameras_and_bitrate(road_length, camera_range, frame_rate, frame_size, num_colors)

# Results
print(f"\nNumber of cameras needed: {num_cameras}")
print(f"Required minimum bit-rate for the network (in bits per second): {total_bitrate}")