# -*- coding: utf-8 -*-
"""3.1 Πρόγραμμα λογισμικού, Ελβις Αβντουλι, Ε22001

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120m3y-bH-37r1iWkk-86dpQ0RDYn7URR
"""

def main():

  # Εισαγωγή δεδομένων από το χρήστη
    while True:
        try:
            L = float(input("Εισάγετε το μέγεθος πακέτου L (σε bits): "))
            if L <= 0:
                raise ValueError("Το μέγεθος πακέτου πρέπει να είναι θετικός αριθμός.")
            break
        except ValueError as ve:
            print(ve)

    while True:
        try:
            H = float(input("Εισάγετε το μέγεθος του Header: "))
            if H <= 0:
                raise ValueError("Ο Header πρέπει να είναι θετικός αριθμός.")
            break
        except ValueError as ve:
            print(ve)

    while True:
        try:
            N = int(input("Εισάγετε τον αριθμό των κόμβων που παρεμβάλλονται: "))
            if N < 0:
                raise ValueError("Ο αριθμός των κόμβων πρέπει να είναι θετικός αριθμός.")
            break
        except ValueError as ve:
            print(ve)

    while True:
        try:
            C = float(input("Εισάγετε το bit rate C (σε bits): "))
            if C <= 0:
                raise ValueError("Το bit rate πρέπει να είναι θετικός αριθμός.")
            break
        except ValueError as ve:
            print(ve)

    while True:
        try:
            F = float(input("Εισάγετε τον αριθμό των fragments: "))
            if F < 0:
                raise ValueError("Ο αριθμός των fragments πρέπει να είναι θετικός αριθμός.")
            if F > L:
                raise ValueError("Τα fragments πρέπει να είναι λιγότερα από το μήκος του πακέτου.")
            break
        except ValueError as ve:
            print(ve)

    # Υπολογισμός καθυστέρησης με fragmentations και χωρίς
    if F>0:
      delayFragHead = (((L / F)*(F + H))/C ) + (N - 2) * ((F + H)/ C)
      delayWITHOUTFragANDHead = (N - 1) * (L / C)
    delayFragWITHOUTHead=(L/C)+(N-2)*(F/C)

    # Εκτυπωση καθυστέρησης με fragmentations και χωρίς
    if F>0:
      print("Η καθυστέρηση με fragmentations είναι", delayFragHead)
      print("Η καθυστέρηση χωρίς fragmentations είναι", delayWITHOUTFragANDHead)
    print("Η καθυστέρηση με Fragmentations χωρις header ειναι",delayFragWITHOUTHead)

if __name__ == "__main__":
    main()